### ISSUE TITLE
Cisco Umbrella Block IPs in sunburst-ipv4.csv

### ISSUE THREAD

**Issue by ceb3** [davisshannon/Splunk-Sunburst#1]
146.112.61.104
146.112.61.107

These are Cisco Umbrella OpenDNS Block IPs. https://support.umbrella.com/hc/en-us/articles/115001357688-What-are-the-Cisco-Umbrella-Block-Page-IP-Addresses-

These should not be in the list of IOCs

**Comment by davisshannon** [comment]
Thanks for picking those up.  They were reported by another researcher.  They've now been removed.
